"""Add academic curriculum tables

Revision ID: 0bd063017f25
Revises: 307731f078ca
Create Date: 2026-08-27 01:18:40.167001
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0bd063017f25'
down_revision: Union[str, None] = '307731f078ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_type', sa.String(length=20), nullable=True, server_default='SHS'))
    op.add_column('users', sa.Column('school_university', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('programme', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('semester', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'semester')
    op.drop_column('users', 'programme')
    op.drop_column('users', 'department')
    op.drop_column('users', 'school_university')
    op.drop_column('users', 'student_type')
    # ### end Alembic commands ###