"""Add semester column to users

Revision ID: 1c2d3e4f5g6h
Revises: 0bd063017f25
Create Date: 2026-08-27 01:20:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1c2d3e4f5g6h'
down_revision: Union[str, None] = '0bd063017f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('semester', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'semester')
    # ### end Alembic commands ###