"""add topic progress table

Revision ID: 80f7381889d1
Revises: c435697c653f
Create Date: 2026-09-10 01:35:41.658434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80f7381889d1'
down_revision: Union[str, None] = 'c435697c653f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic_progress')
    )
    op.create_index(op.f('ix_topic_progress_topic_id'), 'topic_progress', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_progress_user_id'), 'topic_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_progress_user_id'), table_name='topic_progress')
    op.drop_index(op.f('ix_topic_progress_topic_id'), table_name='topic_progress')
    op.drop_table('topic_progress')
    # ### end Alembic commands ###
